// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDabo1CY81mZ5r0foV8TMmnTHzEuaFRM5c',
    appId: '1:1027627935829:android:b98984238b1cc0ea7e4cdc',
    messagingSenderId: '1027627935829',
    projectId: 'vardiya-takvimi-fc7eb',
    storageBucket: 'vardiya-takvimi-fc7eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdhDnujmp5J13__qmhj_zwm_N7alhsPYg',
    appId: '1:1027627935829:ios:6c4708336c83ad407e4cdc',
    messagingSenderId: '1027627935829',
    projectId: 'vardiya-takvimi-fc7eb',
    storageBucket: 'vardiya-takvimi-fc7eb.firebasestorage.app',
    androidClientId: '1027627935829-mpq1mrku44jkee29bu037sm045jbtgqj.apps.googleusercontent.com',
    iosClientId: '1027627935829-mriq5g63e4ebultibo0dcas520d79avj.apps.googleusercontent.com',
    iosBundleId: 'com.multistech.vardiyatakip',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtx4NPcCCRKm2NcMQptEl-EXeU7ZYCOAs',
    appId: '1:1027627935829:web:d83e48fd49c067537e4cdc',
    messagingSenderId: '1027627935829',
    projectId: 'vardiya-takvimi-fc7eb',
    authDomain: 'vardiya-takvimi-fc7eb.firebaseapp.com',
    storageBucket: 'vardiya-takvimi-fc7eb.firebasestorage.app',
    measurementId: 'G-JY604M5PH0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdhDnujmp5J13__qmhj_zwm_N7alhsPYg',
    appId: '1:1027627935829:ios:915fcb852cf029ed7e4cdc',
    messagingSenderId: '1027627935829',
    projectId: 'vardiya-takvimi-fc7eb',
    storageBucket: 'vardiya-takvimi-fc7eb.firebasestorage.app',
    androidClientId: '1027627935829-mpq1mrku44jkee29bu037sm045jbtgqj.apps.googleusercontent.com',
    iosClientId: '1027627935829-srk8iibsfib2s74tilpc0n5egplhh4sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtx4NPcCCRKm2NcMQptEl-EXeU7ZYCOAs',
    appId: '1:1027627935829:web:a2f4d37e3ffe78917e4cdc',
    messagingSenderId: '1027627935829',
    projectId: 'vardiya-takvimi-fc7eb',
    authDomain: 'vardiya-takvimi-fc7eb.firebaseapp.com',
    storageBucket: 'vardiya-takvimi-fc7eb.firebasestorage.app',
    measurementId: 'G-TH8TPF2RQD',
  );

}